Invalid HTTP_HOST header: '119.23.59.185:8001'. You may need to add '119.23.59.185' to ALLOWED_HOSTS.
Bad Request: /
[09/May/2019 03:04:17] "GET / HTTP/1.1" 400 60546
Invalid HTTP_HOST header: '119.23.59.185:8001'. You may need to add '119.23.59.185' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[09/May/2019 03:04:18] "GET /favicon.ico HTTP/1.1" 400 60595
Invalid HTTP_HOST header: '119.23.59.185:8001'. You may need to add '119.23.59.185' to ALLOWED_HOSTS.
Bad Request: /blog/index
[09/May/2019 03:04:56] "GET /blog/index HTTP/1.1" 400 60656
Invalid HTTP_HOST header: '119.23.59.185:8001'. You may need to add '119.23.59.185' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[09/May/2019 03:04:57] "GET /favicon.ico HTTP/1.1" 400 60605
[09/May/2019 03:13:56] "GET /blog/index/ HTTP/1.1" 200 5197
[09/May/2019 03:13:58] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:14:00] "GET /blog/archives/ HTTP/1.1" 200 4551
[09/May/2019 03:14:01] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:14:03] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:14:04] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:14:48] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:14:59] "GET /blog/detail/1/ HTTP/1.1" 200 4702
[09/May/2019 03:25:08] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:25:10] "GET /blog/detail/3/ HTTP/1.1" 200 4029
Performing system checks...

System check identified no issues (0 silenced).
May 09, 2019 - 03:13:53
Django version 2.1.8, using settings 'xh_blog.settings'
Starting development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xuhang_blog/personal_blog/xh_blog/xh_blog/settings.py", line 28
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xuhang_blog/personal_blog/xh_blog/xh_blog/settings.py", line 28
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
[09/May/2019 03:44:42] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:44:44] "GET /blog/detail/3/ HTTP/1.1" 200 4029
[09/May/2019 03:44:46] "GET /blog/detail/2/ HTTP/1.1" 200 4023
[09/May/2019 03:44:49] "GET /blog/detail/1/ HTTP/1.1" 200 4702
[09/May/2019 03:45:00] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:45:02] "GET /blog/archives/ HTTP/1.1" 200 4551
[09/May/2019 03:45:08] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:45:10] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:45:11] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:45:12] "GET /blog/archives/ HTTP/1.1" 200 4551
[09/May/2019 03:45:14] "GET / HTTP/1.1" 200 5197
[09/May/2019 03:45:15] "GET /blog/aboutme/ HTTP/1.1" 200 3270
[09/May/2019 03:45:18] "GET / HTTP/1.1" 200 5197
[09/May/2019 05:50:12] "GET /blog/detail/3/ HTTP/1.1" 200 4029
[09/May/2019 05:50:14] "GET / HTTP/1.1" 200 5197
[09/May/2019 05:54:55] "GET / HTTP/1.1" 200 5197
[09/May/2019 05:55:07] "GET /blog/archives/ HTTP/1.1" 200 4551
[09/May/2019 05:55:08] "GET / HTTP/1.1" 200 5197
[09/May/2019 05:55:11] "GET / HTTP/1.1" 200 5197
[09/May/2019 05:55:20] "GET /blog/index/ HTTP/1.1" 200 5197
Performing system checks...

System check identified no issues (0 silenced).
May 09, 2019 - 03:44:38
Django version 2.1.8, using settings 'xh_blog.settings'
Starting development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
[09/May/2019 06:31:25] "GET /blog/index/ HTTP/1.1" 200 5176
[09/May/2019 06:31:39] "GET /blog/index/ HTTP/1.1" 200 5176
[09/May/2019 06:31:41] "GET /blog/feed/ HTTP/1.1" 200 1810
[09/May/2019 06:32:26] "GET /blog/feed/ HTTP/1.1" 200 1810
[09/May/2019 06:32:27] "GET /blog/feed/ HTTP/1.1" 200 1810
[09/May/2019 06:37:36] "GET /blog/index/ HTTP/1.1" 200 5176
[09/May/2019 06:37:38] "GET / HTTP/1.1" 200 5176
[09/May/2019 06:37:39] "GET / HTTP/1.1" 200 5176
[09/May/2019 06:37:42] "GET /blog/detail/1/ HTTP/1.1" 200 4681
[09/May/2019 06:37:45] "GET /blog/index/ HTTP/1.1" 200 5176
[09/May/2019 06:37:46] "GET /blog/index/ HTTP/1.1" 200 5176
[09/May/2019 06:37:48] "GET /blog/archives/ HTTP/1.1" 200 4530
[09/May/2019 06:37:50] "GET /blog/archives/ HTTP/1.1" 200 4530
[09/May/2019 06:37:53] "GET /blog/searchtag/Python HTTP/1.1" 200 4685
[09/May/2019 06:37:56] "GET /blog/searchtag/java HTTP/1.1" 200 3930
[09/May/2019 06:39:37] "GET / HTTP/1.1" 200 5176
[09/May/2019 06:40:12] "GET /blog/search/?s=%E5%8F%8D%E5%B0%84 HTTP/1.1" 200 3654
[09/May/2019 06:41:42] "GET /blog/search/?s=%E5%93%88%E5%93%88 HTTP/1.1" 200 3282
[09/May/2019 06:42:09] "GET /blog/search HTTP/1.1" 301 0
[09/May/2019 06:42:09] "GET /blog/search/ HTTP/1.1" 302 0
[09/May/2019 06:42:10] "GET / HTTP/1.1" 200 5176
[09/May/2019 11:27:17] "GET / HTTP/1.1" 200 5176
Not Found: /favicon.ico
[09/May/2019 11:27:19] "GET /favicon.ico HTTP/1.1" 404 2182
[09/May/2019 11:27:28] "GET / HTTP/1.1" 200 5176
Not Found: /favicon.ico
[09/May/2019 11:27:28] "GET /favicon.ico HTTP/1.1" 404 2182
[09/May/2019 11:28:00] "GET / HTTP/1.1" 200 5176
Not Found: /favicon.ico
[09/May/2019 11:28:00] "GET /favicon.ico HTTP/1.1" 404 2182
[09/May/2019 11:28:08] "GET / HTTP/1.1" 200 5176
Not Found: /favicon.ico
[09/May/2019 11:28:09] "GET /favicon.ico HTTP/1.1" 404 2182
Not Found: /favicon.ico
[09/May/2019 11:28:13] "GET /favicon.ico HTTP/1.1" 404 2182
[09/May/2019 11:28:20] "GET /blog/searchtag/java HTTP/1.1" 200 3930
Not Found: /favicon.ico
[09/May/2019 11:28:20] "GET /favicon.ico HTTP/1.1" 404 2182
Not Found: /favicon.ico
[09/May/2019 11:28:22] "GET /favicon.ico HTTP/1.1" 404 2182
[10/May/2019 02:19:11] "GET / HTTP/1.1" 200 5176
Not Found: /favicon.ico
[10/May/2019 02:19:11] "GET /favicon.ico HTTP/1.1" 404 2182
Performing system checks...

System check identified no issues (0 silenced).
May 09, 2019 - 06:31:22
Django version 2.1.8, using settings 'xh_blog.settings'
Starting development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xuhang_blog/personal_blog/xh_blog/xh_blog/settings.py", line 28
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xuhang_blog/personal_blog/xh_blog/xh_blog/settings.py", line 28
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
